apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-project-name
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-project-name
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/jlafata/spring-project-name.git
      ref:
        branch: main

